version: "3.9"

services:
  customer:
    build: ./customer
    ports:
      - "8081:8081"
    env_file:
      - ./customer/.env
    networks:
      - tesodevNetwork

  mongodb:
    container_name: "mongodb"
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - tesodevNetwork

  order:
    build: ./order
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    env_file:
      - ./order/.env
    networks:
      - tesodevNetwork

  product:
    build: ./product
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    env_file:
      - ./product/.env
    networks:
      - tesodevNetwork

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - tesodevNetwork

networks:
  tesodevNetwork:

volumes:
  mongo_db:
