version: "3.9"

services:
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
    networks:
      - tesodevNetwork

  rabbitmq:
    image: rabbitmq:3.13.0
    container_name: rabbitmq
    ports:
      - 5673:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - tesodevNetwork

  customer:
    build: ./customer
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db
    networks:
      - tesodevNetwork

  order:
    build: ./order
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
      - mongo_db
    environment:
      MONGODB_ORDER_URI: mongodb://mongo_db:2717/orderDB
      MONGODB_AUDIT_URI: mongodb://mongo_db:2717/auditDB
      PORT: 8083
      RABBITMQ_URI: amqp://rabbitmq:5673
      NODEMAILER_USER: brknt.8811@gmail.com
      NODEMAILER_PASS: npvz fzsa tkiz mtug

    networks:
      - tesodevNetwork

  product:
    build: ./product
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - mongo_db
    environment:
      MONGODB_PRODUCT_URI: mongodb://mongo_db:2717/productDB
      RABBITMQ_URI: amqp://rabbitmq:5673
      JWT_SECRET: tesodev_secret
      PORT: 8082
    networks:
      - tesodevNetwork

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    networks:
      - tesodevNetwork

networks:
  tesodevNetwork:

volumes:
  mongo_db:
