version: '3.9'

services:

#customer
  customer:
    build: ./customer
    ports:
      - '8081:8081'
    depends_on:
      - mongoDB

#order
  order:
    build: ./order
    ports:
      - '8083:8083'
    depends_on:
      - mongoDB

#product
  product:
    build: ./product
    ports:
      - '8082:8082'
    depends_on:
      - mongoDB

#api-gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - '8080:8080'
    depends_on:
      - mongoDB

#mongodb
  mongoDB:
    image: mongo:latest
    restart: always
    ports:
      - 2720:27017
    volumes:
      - mongo_db:/data/db

#rabbitmq
  rabbitMQ:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq


volumes:
  mongo_db: {}